version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    groups:
      all-dependencies:
        patterns:
          - '*'
    schedule:
      interval: monthly
